"""Workbook-derived governed reference seed data for patterns and dictionaries."""

from __future__ import annotations

import json
from typing import Any

PATTERNS: list[dict[str, Any]] = json.loads(
    r'''[
  {
    "pattern_id": "#01",
    "name": "Request-Reply",
    "category": "SÍNCRONO",
    "description": "Un sistema pregunta, otro responde, el primero espera — todo en una sola llamada síncrona.",
    "oci_components": "OCI API Gateway — valida JWT/OAuth2, rate limiting y WAF\nOIC Gen3 — mapeo, transformación y llamada al destino\nOracle ORDS — expone tablas Oracle como REST sin código\nOCI APM — trazabilidad end-to-end de latencia y errores",
    "when_to_use": "Consultas que requieren respuesta inmediata\nAPIs con SLA contractual de tiempo de respuesta\nTransacciones donde el cliente espera confirmación\nOperaciones de lectura de alta frecuencia",
    "when_not_to_use": "Usar Request-Reply para operaciones lentas (>30s) — reportes pesados, lotes de registros, emails masivos. El cliente recibe timeouts, el gateway los interpreta como errores y los reintentos sobrecargan el sistema hasta saturarlo. Síntoma clásico: el equipo 'soluciona' el problema subiendo el timeout a 120s — lo que solo oculta el verdadero problema. La solución correcta: responder inmediatamente con un ID de seguimiento y procesar en asíncrono (Event-Driven o Saga).",
    "technical_flow": "Cliente llama con JWT — Gateway valida auth y rate limiting\nOIC Gen3 recibe y transforma: mapeo de campos, XSLT, enriquecimiento\nOIC invoca a Oracle DB vía ORDS — consulta SQL o endpoint REST\nDB responde — OIC formatea la respuesta final al cliente\nAPI Gateway registra: latencia, status code, consumer ID en OCI APM",
    "business_value": "Unifica seguridad y visibilidad en un único punto. Centraliza OAuth2, rate limiting y logging — reduciendo hasta un 60% la latencia de integraciones punto a punto y permitiendo medir SLAs con socios externos de forma automática."
  },
  {
    "pattern_id": "#02",
    "name": "Event-Driven / Pub-Sub",
    "category": "ASÍNCRONO",
    "description": "Alguien publica que algo ocurrió. Quien quiera enterarse, se suscribe. El que publica no sabe quién escucha.",
    "oci_components": "OCI Streaming — broker Kafka compatible, retención configurable\nOIC Gen3 Kafka Adapter — produce y consume con mapeo visual\nOCI GoldenGate Stream Analytics (GGSA) — filtra y procesa eventos en vuelo\nOCI Functions — se activa automáticamente al llegar mensajes",
    "when_to_use": "Un dato va a múltiples sistemas simultáneamente\nProductores y consumidores a ritmos distintos\nNecesitas replay o auditoría de eventos\nAlta frecuencia: > 1,000 mensajes por segundo",
    "when_not_to_use": "Asumir que Kafka garantiza exactly-once. Por defecto es at-least-once — un mensaje puede entregarse más de una vez si el consumidor falla antes de confirmar. Segundo error frecuente: asumir orden global entre mensajes. Kafka garantiza orden dentro de una partición, no entre particiones. Para pagos o contratos donde un duplicado es inaceptable, usar Transactional Outbox (#09).",
    "technical_flow": "JDE genera evento (ej: orden creada) — OIC Kafka Adapter serializa y publica\nOCI Streaming enruta al topic correspondiente — sin coupling con el productor\nConsumidor A (OIC Workflows) lee del topic y procesa su lógica de negocio\nConsumidor N (Analytics) lee el mismo mensaje — replay ilimitado sin afectar JDE\nGoldenGate Stream Analytics detecta patrones anómalos en vuelo en tiempo real",
    "business_value": "Elimina la dependencia directa entre sistemas. Cada nuevo sistema que necesita un evento se conecta sin tocar el que lo publica — sin coordinación entre equipos, sin riesgo de romper lo que ya funciona en producción."
  },
  {
    "pattern_id": "#03",
    "name": "API Facade",
    "category": "SEGURIDAD / PERFORMANCE",
    "description": "Una capa delgada entre el cliente y la base de datos que responde en milisegundos sin el peso de un orquestador completo.",
    "oci_components": "OCI API Gateway — seguridad, throttling, WAF, developer portal\nOCI Functions — lógica serverless, escala a cero, pago por invocación\nOracle ORDS — expone tablas Oracle como REST sin código adicional\nOCI APM — observabilidad completa de latencia por endpoint",
    "when_to_use": "APIs simples de consulta o escritura directa\nLatencia < 50ms como requerimiento estricto\nLógica stateless sin orquestación compleja\nEndpoints que escalan a cero en inactividad",
    "when_not_to_use": "Usar Functions para lógica que necesita orquestación: llamar a tres sistemas distintos, manejar errores de negocio complejos, coordinar procesos con estado entre llamadas. Functions no tiene persistencia natural ni mecanismos de retry configurables visualmente. El síntoma: un archivo de Function que crece a 500 líneas con reintentos manuales y llamadas encadenadas a múltiples sistemas — eso ya es un orquestador informal que nadie puede monitorear. En ese caso usar OIC Gen3 Integration Flow.",
    "technical_flow": "Cliente llama con API Key u OAuth2 — Gateway valida identidad en < 5ms\nGateway aplica rate limiting, WAF (inyección SQL, DDoS) y políticas CORS\nOCI Functions ejecuta lógica stateless: validaciones, enriquecimiento de datos\nORDS ejecuta SQL optimizado en Oracle DB y retorna JSON al Function\nRespuesta sube la cadena — cliente recibe resultado en < 50ms totales",
    "business_value": "Latencia bajo 50ms para operaciones simples — imposible con middleware enterprise. Costo por invocación en lugar de instancia permanente. Para APIs de catálogo de alta frecuencia, la diferencia de costo respecto a OIC es de un orden de magnitud."
  },
  {
    "pattern_id": "#04",
    "name": "Saga / Compensación",
    "category": "RESILIENCIA",
    "description": "Una transacción de negocio que abarca múltiples sistemas: si algo falla en el camino, deshace todo en orden inverso.",
    "oci_components": "OIC Gen3 Process Automation — orquestador con estado visible en dashboard\nOCI Streaming — transporta eventos de compensación entre pasos\nOCI Functions — ejecuta pasos de negocio stateless dentro de la Saga\nOracle DB — persiste el estado de cada Saga para recovery ante fallos",
    "when_to_use": "Transacciones que abarcan múltiples sistemas\nCuando 2PC (two-phase commit) es imposible\nProcesos con pasos reversibles (orden · pago · despacho)\nMicroservicios sin base de datos compartida",
    "when_not_to_use": "Implementar pasos que no son idempotentes. Si OIC reinvoca 'cobrar pago' porque hubo un timeout (sin que el primer cobro haya fallado, solo tardado en responder), el cliente puede ser cobrado dos veces. Cada paso debe poder ejecutarse N veces produciendo el mismo resultado. Sin idempotencia, los reintentos automáticos de OIC se convierten en duplicados de negocio.",
    "technical_flow": "OIC Process recibe la solicitud y comienza la Saga — guarda estado inicial\nPaso 1: Crea orden en ERP — OK → guarda estado ORDEN_CREADA\nPaso 2: Reserva stock en WMS — OK → guarda estado STOCK_RESERVADO\nPaso 3: Cobro falla → OIC inicia compensaciones en orden inverso\nLiberar stock → Cancelar orden — sin bloquear tablas, sin 2PC",
    "business_value": "Permite ejecutar transacciones complejas que abarcan sistemas de distintos proveedores sin 2PC ni coordinadores distribuidos. La consistencia eventual reemplaza a la inmediata, con garantía de que el sistema siempre termina en un estado válido."
  },
  {
    "pattern_id": "#05",
    "name": "CDC — Change Data Capture",
    "category": "DATOS",
    "description": "La base de datos como fuente de eventos: cada INSERT, UPDATE o DELETE se captura y publica en tiempo real.",
    "oci_components": "Oracle GoldenGate — captura del redo log sin impacto en aplicaciones\nOCI Streaming — distribuye los eventos CDC a todos los consumidores\nOCI Data Integration / Data Integrator — prepara, transforma o carga datos downstream según el caso\nOIC Kafka Adapter / conectores batch — consume eventos o dispara procesos posteriores",
    "when_to_use": "Sincronizar DB con sistemas downstream en tiempo real\nAlimentar data lake o warehouse sin polling\nInvalidar cachés cuando cambia la fuente de datos\nAuditoría inmutable de todos los cambios en DB",
    "when_not_to_use": "GoldenGate requiere licencia separada. Verificar licenciamiento antes de incluir en el diseño de arquitectura. No usar CDC si el volumen de cambios es muy bajo y el polling simple es suficiente — la complejidad no justificaría el costo de GoldenGate para escenarios de baja frecuencia.",
    "technical_flow": "App escribe en Oracle DB de forma normal — sin ningún cambio en la aplicación\nGoldenGate lee el Redo Log capturando cada INSERT / UPDATE / DELETE\nGoldenGate publica el cambio al topic correspondiente en OCI Streaming\nData Lake consume en tiempo real — sin polling, sin queries periódicas\nAnalytics y ML reaccionan al cambio en < 1 seg con datos completamente frescos",
    "business_value": "Transforma la base de datos en una fuente de eventos en tiempo real sin tocar el código de la aplicación. Elimina los procesos batch nocturnos y permite que los sistemas analíticos reaccionen a los cambios en milisegundos en lugar de horas."
  },
  {
    "pattern_id": "#06",
    "name": "Strangler Fig Runtime",
    "category": "MIGRACIÓN",
    "description": "Migrar un sistema legacy incrementalmente mientras sigue en producción, sin que nadie lo note.",
    "oci_components": "OCI API Gateway — routing table configurable, enruta por integración/ruta\nOIC Gen3 — destino de las integraciones ya migradas\nRuntime legacy actual — origen, continúa operando para las no migradas\nOCI Logging — audita qué ruta toma cada request, visibilidad del progreso",
    "when_to_use": "Migrar middleware legacy a OIC sin downtime ni Big Bang\nNecesitas rollback instantáneo por integración\nClientes externos no pueden cambiar sus endpoints\nEquipos migran integraciones en paralelo e independiente",
    "when_not_to_use": "Mantener la coexistencia del stack target con el stack legacy indefinidamente. El Strangler Fig es una estrategia de migración con fecha de fin, no una arquitectura permanente. Dos stacks en producción significan operaciones duplicadas y complejidad técnica sostenida. El patrón de fallo clásico: no se define una fecha de corte desde el inicio y la organización termina operando el runtime legacy por tiempo indefinido.",
    "technical_flow": "Cliente llama siempre al mismo endpoint — OCI API Gateway recibe la petición\nGateway consulta Routing Table: ¿integración ya migrada? → OIC Gen3\nSi aún en runtime legacy → enruta al runtime legacy actual (ruta legacy, transparente al cliente)\nIntegración migrada → enruta a OIC Gen3 — cliente recibe misma respuesta\nRollback: cambiar routing table en < 30 seg sin código ni deploy",
    "business_value": "Elimina el riesgo de las migraciones Big Bang. Cada integración migrada es un win validado en producción antes de continuar. Si algo falla, se revierte en segundos sin impacto al negocio. Una migración completa puede realizarse en 12 meses sin ningún downtime."
  },
  {
    "pattern_id": "#07",
    "name": "Scatter-Gather",
    "category": "SÍNCRONO",
    "description": "Pregunta a N sistemas en paralelo, recibe todas las respuestas, regresa un resultado consolidado.",
    "oci_components": "OIC Gen3 Parallel Flow — implementación nativa con configuración visual\nOCI Functions — para llamadas paralelas ligeras sin overhead de OIC\nOCI APM — traza cada rama paralela, identifica el cuello de botella\nOracle Integration Adapters — conectores pre-construidos por sistema destino",
    "when_to_use": "Consulta de stock en múltiples almacenes o sistemas\nPrecio en tiempo real de múltiples proveedores\nCualquier fan-out y re-agrupación de resultados\nReducir latencia total de N consultas secuenciales",
    "when_not_to_use": "No diseñar para fallos parciales. Si uno de cinco sistemas no responde, el agregador debe decidir explícitamente qué hacer: ¿devuelve resultado con los datos disponibles? ¿Usa el último valor del caché? ¿Falla la operación completa? No gestionarlo convierte la disponibilidad del scatter-gather en el producto de la disponibilidad de cada sistema: 99% × 99% × 99% × 99% × 99% = 95%.",
    "technical_flow": "Cliente hace una petición única al endpoint — API Gateway recibe y enruta a OIC\nOIC Scatter divide la petición y llama a N sistemas EN PARALELO simultáneamente\nSistema A responde (ej: stock local) — OIC espera según estrategia configurada\nSistema B y N responden independientemente — sin esperar al anterior\nOIC Gather consolida todos los resultados y retorna una respuesta unificada",
    "business_value": "Reduce la latencia al tiempo del sistema más lento, no la suma de todos. En portales B2B y e-commerce, cada segundo adicional reduce directamente la tasa de conversión. La diferencia entre 6s y 2s en una consulta de disponibilidad es la diferencia entre un portal que convierte y uno que el usuario abandona."
  },
  {
    "pattern_id": "#08",
    "name": "Circuit Breaker",
    "category": "RESILIENCIA",
    "description": "Si un sistema falla repetidamente, deja de llamarlo — responde con datos alternativos y avisa al equipo.",
    "oci_components": "OIC Gen3 Error Handling — fault bindings, retry con backoff exponencial\nOCI Monitoring + Alarms — detecta el patrón de error antes de que el usuario lo note\nRedis / OCI Cache — almacena valores de fallback para responder con circuito abierto\nOIC Process — escalación automática si el circuito lleva más de X minutos abierto",
    "when_to_use": "Integración con sistemas legacy inestables (JDE, SAP)\nDependencias de terceros fuera de tu SLA\nPrevenir cascade failures en plataformas integradas\nMejorar UX cuando un backend downstream falla",
    "when_not_to_use": "Confundir Circuit Breaker con Retry — son complementarios, no alternativos. Retry es para fallos transitorios (red inestable, timeout momentáneo) — intenta de nuevo con backoff exponencial 2-3 veces. Circuit Breaker es para cuando el sistema está genuinamente degradado — deja de intentar para no empeorarlo. Un Retry sin Circuit Breaker bombardea con reintentos un sistema ya caído, agravando el problema.",
    "technical_flow": "Canal digital llama a OIC — OIC intenta conectar con JDE (circuito CERRADO)\nJDE empieza a fallar — OIC aplica retry con backoff exponencial: 1s, 2s, 4s\n5 fallos consecutivos: circuito ABRE — llamadas a JDE bloqueadas automáticamente\nOIC retorna respuesta de caché inmediata — usuario no percibe ningún error\nTimeout → HALF-OPEN: prueba 1 request para verificar si JDE se recuperó",
    "business_value": "Previene que la degradación de un sistema legacy destruya la experiencia del canal digital. El sistema que falla lo hace de forma aislada y controlada. El canal sigue operando con datos alternativos mientras el equipo responsable trabaja en la solución."
  },
  {
    "pattern_id": "#09",
    "name": "Transactional Outbox",
    "category": "DATOS / GARANTÍAS",
    "description": "Garantiza que si un dato se guarda en la base de datos, su evento correspondiente siempre se publicará — sin excepción.",
    "oci_components": "Oracle DB — tabla OUTBOX_EVENTS en la misma transacción, mismo commit\nOracle GoldenGate — Relay usando CDC, lee OUTBOX sin impacto adicional en DB\nOCI Streaming — broker que recibe los eventos publicados por el Relay\nOIC Kafka Adapter — consumidor idempotente con manejo de duplicados",
    "when_to_use": "Operaciones financieras: pagos, facturación, contratos\nCuando perder un evento significa perder negocio\nCompliance con reguladores o auditores externos\nNecesitas garantía exactly-once en la entrega",
    "when_not_to_use": "No implementar idempotencia en los consumidores. El Relay puede publicar el mismo evento más de una vez — si falla antes de confirmar el procesamiento, en el próximo ciclo publicará de nuevo. Los consumidores que descuentan inventario o activan contratos deben reconocer duplicados por ID único del evento. Segundo error frecuente: no implementar una política de retención que archive o elimine los registros procesados de la tabla OUTBOX. Sin limpieza, la tabla crece indefinidamente afectando el rendimiento de la base de datos transaccional.",
    "technical_flow": "OIC inicia TX ACID: escribe en PEDIDOS y en OUTBOX_EVENTS simultáneamente\nOracle DB hace COMMIT atómico — si falla, ninguna tabla fue modificada\nGoldenGate detecta nuevo registro en OUTBOX via CDC del Redo Log\nGoldenGate publica evento a OCI Streaming con Idempotency Key único\nConsumidor descarta duplicados con Idempotency Key — exactly-once garantizado",
    "business_value": "Elimina la inconsistencia entre la base de datos y el broker de mensajes — el problema más frecuente y difícil de diagnosticar en integraciones asíncronas. Para transacciones financieras o contractuales, la garantía de entrega exacta no es opcional."
  },
  {
    "pattern_id": "#10",
    "name": "CQRS + Event Sourcing",
    "category": "DATOS / AVANZADO",
    "description": "Separar lecturas de escrituras, y guardar el historial completo de cambios en lugar del estado actual.",
    "oci_components": "OCI Streaming — Event Store append-only, todos los eventos en orden\nOIC Gen3 — proyecta eventos hacia múltiples Read Models en Oracle DB\nOracle Analytics Cloud — consume Read Models sin impactar el transaccional\nOracle DB — almacena los Read Models materializados por caso de uso",
    "when_to_use": "Lecturas y escrituras con patrones de carga muy distintos\nMúltiples vistas del mismo dato para distintos consumidores\nAuditoría completa e inmutable de todos los cambios\nReconstruir el estado histórico en cualquier momento",
    "when_not_to_use": "Aplicar CQRS/Event Sourcing a sistemas simples. Un CRUD con 5 tablas no lo necesita. La consistencia eventual entre Write y Read Models confunde a usuarios que acaban de escribir un dato y no lo ven de inmediato. Depurar un sistema Event Sourced es fundamentalmente diferente: para entender el estado actual de un objeto tienes que reproducir su historia completa de eventos. Solo tiene sentido cuando la escala o los requisitos de auditoría lo justifican inequívocamente.",
    "technical_flow": "Command llega a OIC Process — valida reglas de negocio y autorización\nOIC escribe evento al Event Store (Oracle DB append-only) — NUNCA modifica registros\nOCI Streaming publica el evento a los topics correspondientes\nOIC Gen3 proyecta el evento: actualiza cada Read Model materializado\nConsumidores (mobile, analytics, partners) leen desde su Read Model optimizado",
    "business_value": "Permite escalar lecturas y escrituras de forma completamente independiente. La auditoría completa e inmutable del historial de eventos elimina preguntas de compliance que de otra forma requieren semanas de análisis manual."
  },
  {
    "pattern_id": "#11",
    "name": "BFF — Backend for Frontend",
    "category": "API DESIGN",
    "description": "Una API por tipo de cliente: app móvil, portal web y dispositivos IoT tienen APIs distintas, adaptadas a sus necesidades.",
    "oci_components": "OCI Functions — BFF ligero para móvil e IoT, latencia y costo críticos\nOIC Gen3 — BFF complejo para web/B2B con múltiples sistemas backend\nOCI API Gateway — punto de entrada que enruta a cada BFF por canal\nOracle APIM Developer Portal — documentación separada por canal/BFF",
    "when_to_use": "Clientes con necesidades de datos muy distintas\nRedes con limitaciones: IoT, móvil en campo\nEquipos frontend que necesitan autonomía de API\nOptimizar latencia y payload por tipo de dispositivo",
    "when_not_to_use": "Duplicar lógica de negocio en cada BFF. Si el BFF de móvil y el de web implementan cada uno su propia lógica para calcular precios con descuento, cuando esa lógica cambia hay que actualizarla en dos lugares y eventualmente se desincronizarán. La frontera debe ser explícita: los BFFs son responsables de transformación y formateo por canal. La lógica de negocio pertenece al sistema core.",
    "technical_flow": "Cliente llama — API Gateway identifica el canal (Mobile/Web/IoT) y enruta\nBFF Mobile: agrega llamadas, filtra a campos mínimos, optimiza para batería\nBFF IoT: traduce REST a MQTT/CBOR binario — compatible con redes LPWAN\nBFF Web: retorna datos completos con paginación para dashboard detallado\nAPI Core es compartido — lógica de negocio en un solo lugar sin duplicación",
    "business_value": "Reduce el payload de respuesta en móvil hasta un 70% al enviar solo los campos necesarios. Cada equipo de frontend tiene autonomía total para evolucionar su API sin coordinación con otros canales — ciclos más rápidos y experiencia optimizada por dispositivo."
  },
  {
    "pattern_id": "#12",
    "name": "Data Mesh",
    "category": "ARQUITECTURA / DATOS",
    "description": "Los datos como producto con dueños por dominio: cada área de negocio es responsable de sus datos.",
    "oci_components": "Oracle Data Catalog — catálogo de descubrimiento de productos de datos\nOCI Object Storage — almacenamiento con control de acceso por dominio\nOracle Analytics Cloud — consumo self-service sin intermediarios\nOCI Data Integration / Data Integrator + GoldenGate — pipelines que cada dominio opera autónomamente",
    "when_to_use": "Organización con múltiples dominios de negocio maduros\nData lake centralizado que se convirtió en bottleneck\nEquipos que esperan semanas para acceder a sus datos\nEscalar datos sin hacer crecer el equipo central",
    "when_not_to_use": "Adoptar Data Mesh como iniciativa tecnológica sin el cambio organizacional. Instalar Oracle Data Catalog y declarar 'tenemos Data Mesh' no resuelve el bottleneck si los equipos de negocio no asumen genuinamente el ownership — con los recursos técnicos y el presupuesto para gestionarlos. Data Mesh requiere que los equipos de negocio pasen a ser responsables de la calidad, disponibilidad y SLA de sus datos. Sin ese accountability real, la plataforma existe pero el cuello de botella permanece.",
    "technical_flow": "Equipo de dominio diseña su Data Product con SLA, schema y tests de calidad\nOIC / GoldenGate construye el pipeline de datos del dominio de forma autónoma\nData Product publicado en OCI Object Storage con versioning y documentación\nOracle Data Catalog registra el producto — descubrimiento self-service\nConsumidores acceden directamente sin tickets a IT — Governance federada",
    "business_value": "Transforma la organización de datos de un equipo central sobrecargado a múltiples equipos especializados. Reduce el tiempo de acceso a nuevos datasets de semanas a días, y habilita analytics en tiempo real sobre datos que antes tardaban días en estar disponibles."
  },
  {
    "pattern_id": "#13",
    "name": "Zero-Trust Integration",
    "category": "SEGURIDAD",
    "description": "Ningún servicio, red o usuario es confiable por defecto — cada llamada se autentica y autoriza explícitamente.",
    "oci_components": "OCI IAM + Identity Domains — gestión centralizada de identidades y políticas\nOCI API Gateway — valida JWT/OAuth2 en cada llamada antes de llegar a servicios\nIstio/Envoy en OKE — implementa mTLS automáticamente entre todos los servicios\nOCI Cloud Guard + Security Zones — monitoreo continuo de comportamiento anómalo",
    "when_to_use": "Integraciones que cruzan perímetros de red\nAcceso de socios externos (B2B, partners)\nRegulaciones: GDPR, PCI-DSS, NOM compliance\nMúltiples nubes o arquitecturas on-prem + cloud",
    "when_not_to_use": "Intentar implementar Zero-Trust en toda la organización al mismo tiempo — la complejidad paraliza el proyecto. La implementación debe ser incremental: primero integraciones con sistemas externos y datos sensibles, luego integraciones internas de alta criticidad, finalmente el resto. Error frecuente: confundir Zero-Trust con mero cifrado en tránsito (TLS). TLS cifra el canal, pero no autentica quién llama. Se necesitan certificados mutuos (mTLS) y tokens de identidad por llamada.",
    "technical_flow": "Cualquier llamada llega con JWT/OAuth2 — Gateway valida identidad sin importar origen\nGateway verifica que el token tiene solo los scopes necesarios — mínimo privilegio\nIstio/Envoy en OKE establece mTLS mutuo entre todos los servicios internos\nOCI Cloud Guard inspecciona cada request en tiempo real — detecta anomalías\nServicio comprometido queda aislado en su scope — sin movimiento lateral posible",
    "business_value": "Reduce la superficie de ataque al mínimo. Si un servicio es comprometido, el impacto está contenido a lo que ese servicio específicamente tenía autorización de hacer. Para datos regulados o contratos enterprise, Zero-Trust es frecuentemente un requisito contractual."
  },
  {
    "pattern_id": "#14",
    "name": "AsyncAPI + Event Catalog",
    "category": "API DESIGN / ASÍNCRONO",
    "description": "El OpenAPI de los sistemas asíncronos — documenta, descubre y gobierna tus APIs de eventos.",
    "oci_components": "OCI Streaming — broker Kafka compatible con schema registry para gobernanza\nOCI API Gateway — documenta y publica el catálogo de APIs síncronas y asíncronas\nOIC Gen3 — consume y produce eventos con validación automática de schema\nOracle APIM Developer Portal — portal de descubrimiento para APIs y eventos",
    "when_to_use": "Organización con múltiples equipos produciendo y consumiendo eventos\nNecesitas gobernanza y versionado de schemas de eventos\nAuditores o socios externos requieren documentación de APIs asíncronas\nEscalar el modelo event-driven sin perder control del contrato de eventos",
    "when_not_to_use": "Implementar AsyncAPI sin disciplina de mantenimiento. Una especificación desactualizada es peor que no tenerla — los consumidores confían en el contrato documentado y una discrepancia produce fallos difíciles de diagnosticar. El catálogo solo aporta valor si el proceso de publicación de nuevos eventos incluye obligatoriamente actualizar la especificación.",
    "technical_flow": "Equipo define el contrato del evento en AsyncAPI spec (schema, topic, versión)\nEvent Catalog registra el nuevo evento — visible para toda la organización\nProductor implementa el evento según el contrato definido\nConsumidor descubre el evento en el catálogo y se suscribe al topic\nSchema Registry valida automáticamente que los mensajes cumplen el contrato",
    "business_value": "Elimina la dependencia informal entre equipos para entender qué eventos existen y qué formato tienen. Cada equipo puede descubrir y consumir eventos de forma autónoma, reduciendo el tiempo de integración de semanas a horas."
  },
  {
    "pattern_id": "#15",
    "name": "AI-Augmented Integration",
    "category": "IA / INTELIGENCIA ARTIFICIAL",
    "description": "La inteligencia artificial como componente activo del flujo de integración — no solo como destino de los datos.",
    "oci_components": "OIC Gen3 AI Agents — soporte MCP para invocar LLMs como pasos de integración\nOCI Language Service — clasificación, sentimiento y extracción de entidades en texto\nOCI Anomaly Detection — detección de anomalías en streams de datos en tiempo real\nOCI Generative AI — Oracle Cohere para generación y transformación de contenido",
    "when_to_use": "Clasificación automática de documentos o mensajes entrantes\nDetección de anomalías en tiempo real en flujos de datos\nEnriquecimiento de datos con entidades extraídas por NLP\nPersonalización de respuestas basada en contexto de IA generativa",
    "when_not_to_use": "Usar IA para lógica de negocio determinística que puede implementarse con reglas explícitas. Si la clasificación siempre sigue las mismas reglas sin ambigüedad, un decision table en OIC es más predecible, auditable y rápido que un modelo de IA. La IA agrega latencia y costo por invocación — solo se justifica cuando el problema tiene genuina ambigüedad o variabilidad que las reglas explícitas no pueden manejar.",
    "technical_flow": "Mensaje o evento llega al flujo OIC Gen3\nOIC invoca OCI AI Service como paso de orquestación (con retry y error handling)\nEl servicio de IA enriquece, clasifica o transforma el payload\nOIC usa el resultado de IA para enrutar o transformar el mensaje\nEl mensaje enriquecido llega al sistema destino con contexto de IA incorporado",
    "business_value": "Permite automatizar decisiones de enrutamiento y transformación que antes requerían intervención humana o reglas explícitas frágiles. Reduce el tiempo de procesamiento manual y escala decisiones complejas a velocidad de máquina."
  },
  {
    "pattern_id": "#16",
    "name": "Integration Mesh",
    "category": "ARQUITECTURA",
    "description": "Una malla de integración distribuida donde cada servicio se comunica sin un orquestador central único.",
    "oci_components": "Istio on OKE — service mesh con mTLS automático, observabilidad y traffic management\nOCI API Gateway — entrada del tráfico externo con gobernanza centralizada\nOIC Gen3 — orquestador para flujos de negocio complejos multi-sistema\nOCI Monitoring — observabilidad end-to-end de la malla de servicios",
    "when_to_use": "Arquitectura de microservicios con múltiples equipos y dominios\nNecesitas observabilidad distribuida del tráfico entre servicios\nRequisitos de seguridad zero-trust en comunicación interna\nEscalar integración sin hacer crecer el equipo central de integración",
    "when_not_to_use": "Adoptar Integration Mesh sin la madurez organizacional necesaria. Requiere equipos con experiencia en Kubernetes, Istio y service mesh — la curva de aprendizaje es significativa. Para organizaciones con pocos servicios o equipos pequeños, la complejidad operativa de gestionar la malla supera los beneficios. Comenzar con OIC como orquestador central y evolucionar hacia la malla cuando el volumen y número de equipos lo justifiquen.",
    "technical_flow": "Servicio A necesita comunicarse con Servicio B\nEl proxy Envoy de A intercepta la llamada y aplica políticas de red\nIstio gestiona el descubrimiento, balanceo y circuit breaking de forma transparente\nmTLS se establece automáticamente sin cambios en el código de la aplicación\nOCI Monitoring registra métricas de latencia, errores y tráfico de toda la malla",
    "business_value": "Permite que múltiples equipos desarrollen y desplieguen servicios de integración de forma independiente sin coordinación central. La observabilidad automática de toda la malla reduce el tiempo de diagnóstico de incidentes de horas a minutos."
  },
  {
    "pattern_id": "#17",
    "name": "Webhook Fanout",
    "category": "ASÍNCRONO / API",
    "description": "Un evento entrante de webhook se distribuye automáticamente a múltiples sistemas sin que el emisor lo sepa.",
    "oci_components": "OCI API Gateway — recibe el webhook, valida firma HMAC del emisor\nOIC Gen3 — fanout paralelo con transformación independiente por destino\nOCI Streaming — buffer si un destino está temporalmente no disponible\nOCI Functions — transformación lightweight por destino en paralelo",
    "when_to_use": "Recibir webhooks de sistemas SaaS externos (GitHub, Stripe, Salesforce)\nUn evento externo debe notificar a múltiples sistemas internos\nNecesitas transformaciones distintas del mismo evento por sistema destino\nReintentos independientes por destino sin afectar a los demás",
    "when_not_to_use": "Usar Webhook Fanout para eventos de alta frecuencia sin control de rate. Si el sistema externo puede enviar miles de webhooks por segundo en picos, el fanout puede saturar los sistemas destino sin mecanismo de backpressure. Para alta frecuencia, el patrón correcto es Event-Driven (#02) con OCI Streaming como buffer entre el receptor del webhook y los consumidores.",
    "technical_flow": "Sistema externo publica webhook al endpoint de OCI API Gateway\nGateway valida la firma HMAC y enruta a OIC Gen3\nOIC Gen3 inicia el fanout: transforma el evento para cada destino en paralelo\nCada destino recibe su versión transformada con retry independiente\nOIC registra el resultado de entrega por destino — visibilidad centralizada",
    "business_value": "Simplifica la integración con sistemas SaaS externos — el emisor solo conoce un endpoint. Nuevos sistemas internos se agregan sin tocar la configuración del emisor ni solicitar cambios a terceros. Los reintentos independientes garantizan que un destino lento o caído no afecte a los demás."
  }
]'''
)

DICTIONARY_OPTIONS: list[dict[str, Any]] = [
    {
        "category": "FREQUENCY",
        "code": "FQ01",
        "value": "Cada 5 minutos",
        "description": "Tipo: Programada. Usar para: Alta frecuencia explícita. Estatus: Válido.",
        "executions_per_day": 288.0,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ02",
        "value": "Cada 15 minutos",
        "description": "Tipo: Programada. Usar para: Alta frecuencia explícita. Estatus: Válido.",
        "executions_per_day": 96.0,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ03",
        "value": "Cada 20 minutos",
        "description": "Tipo: Programada. Usar para: Alta frecuencia explícita. Estatus: Válido.",
        "executions_per_day": 72.0,
        "sort_order": 3,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ04",
        "value": "Cada 30 minutos",
        "description": "Tipo: Programada. Usar para: Alta frecuencia explícita. Estatus: Válido.",
        "executions_per_day": 48.0,
        "sort_order": 4,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ05",
        "value": "Cada 1 hora",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 24.0,
        "sort_order": 5,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ06",
        "value": "Cada 2 horas",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 12.0,
        "sort_order": 6,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ07",
        "value": "Cada 4 horas",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 6.0,
        "sort_order": 7,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ08",
        "value": "Cada 6 horas",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 4.0,
        "sort_order": 8,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ09",
        "value": "Cada 8 horas",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 3.0,
        "sort_order": 9,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ10",
        "value": "Cada 12 horas",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 2.0,
        "sort_order": 10,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ11",
        "value": "Una vez al día",
        "description": "Tipo: Programada. Usar para: Frecuencia estándar. Estatus: Válido.",
        "executions_per_day": 1.0,
        "sort_order": 11,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ12",
        "value": "Semanal",
        "description": "Tipo: Programada. Usar para: Baja frecuencia. Estatus: Válido.",
        "executions_per_day": 0.142857,
        "sort_order": 12,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ13",
        "value": "Quincenal",
        "description": "Tipo: Programada. Usar para: Baja frecuencia. Estatus: Válido.",
        "executions_per_day": 0.066667,
        "sort_order": 13,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ14",
        "value": "Mensual",
        "description": "Tipo: Programada. Usar para: Baja frecuencia. Estatus: Válido.",
        "executions_per_day": 0.033333,
        "sort_order": 14,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ15",
        "value": "Tiempo Real",
        "description": "Tipo: Evento / continuo. Usar para: Proxy batch equivalente; validar diseño final. Estatus: Válido con cautela.",
        "executions_per_day": 24.0,
        "sort_order": 15,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ16",
        "value": "Bajo demanda",
        "description": "Tipo: Eventual. Usar para: Proxy inicial; confirmar luego. Estatus: Válido con cautela.",
        "executions_per_day": 1.0,
        "sort_order": 16,
        "version": "1.0.0",
    },
    {"category": "TRIGGER_TYPE", "code": "TRG01", "value": "Scheduled", "sort_order": 1, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG02", "value": "REST", "sort_order": 2, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG03", "value": "Event", "sort_order": 3, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG04", "value": "FTP/SFTP", "sort_order": 4, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG05", "value": "DB Polling", "sort_order": 5, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG06", "value": "JMS", "sort_order": 6, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG07", "value": "Kafka", "sort_order": 7, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG08", "value": "Webhook", "sort_order": 8, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG09", "value": "SOAP", "sort_order": 9, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX01", "value": "Bajo", "sort_order": 1, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX02", "value": "Medio", "sort_order": 2, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX03", "value": "Alto", "sort_order": 3, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA01", "value": "OK", "sort_order": 1, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA02", "value": "REVISAR", "sort_order": 2, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA03", "value": "PENDING", "sort_order": 3, "version": "1.0.0"},
    {
        "category": "TOOLS",
        "code": "T01",
        "value": "OIC Gen3",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: Msgs/mes, packs/h, pico/h.",
        "is_volumetric": True,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T02",
        "value": "OCI Streaming",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: GB/mes, particiones.",
        "is_volumetric": True,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T03",
        "value": "OCI Queue",
        "description": "Type: Complemento. Volumetry: direct. Metric/proxy: Requests/mes.",
        "is_volumetric": True,
        "sort_order": 3,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T04",
        "value": "OCI Functions",
        "description": "Type: Complemento. Volumetry: direct. Metric/proxy: Invocaciones y GB-sec.",
        "is_volumetric": True,
        "sort_order": 4,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T05",
        "value": "OCI Data Integration",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: GB procesados y pipeline runs.",
        "is_volumetric": True,
        "sort_order": 5,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T06",
        "value": "Data Integrator",
        "description": "Type: Core / tradicional. Volumetry: proxy. Metric/proxy: Jobs/mes (proxy).",
        "is_volumetric": True,
        "sort_order": 6,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T07",
        "value": "Oracle GoldenGate",
        "description": "Type: Core / CDC. Volumetry: proxy. Metric/proxy: Cambios/mes (proxy).",
        "is_volumetric": True,
        "sort_order": 7,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO01",
        "value": "OCI API Gateway",
        "description": "Type: Adicional / proxy. Volumetry: proxy. Typical use: Entrada / salida API protegida. Capture rule: Usar valor individual; si hay más de uno, separar por coma.",
        "is_volumetric": True,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO02",
        "value": "Process Automation",
        "description": "Type: Adicional / proxy. Volumetry: proxy. Typical use: Procesos con estado / saga. Capture rule: Usar valor individual; si hay más de uno, separar por coma.",
        "is_volumetric": True,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO03",
        "value": "OCI Events",
        "description": "Type: Adicional / proxy. Volumetry: proxy. Typical use: Eventos administrados. Capture rule: Usar valor individual; si hay más de uno, separar por coma.",
        "is_volumetric": True,
        "sort_order": 3,
        "version": "1.0.0",
    },
]

CANVAS_COMBINATIONS: list[dict[str, Any]] = [
    {
        "code": "G01",
        "name": "Synchronous app-to-app orchestration",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#01", "#07"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Simple app-to-app integration without additional decoupling.",
        "status": "Valid",
    },
    {
        "code": "G02",
        "name": "Protected synchronous API",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#01", "#03", "#11"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Use when the integration enters or exits through a protected API edge.",
        "status": "Valid",
    },
    {
        "code": "G03",
        "name": "Brokered event backbone",
        "capture_standard": "OIC Gen3, OCI Streaming, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Streaming", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#10", "#14", "#17"],
        "activates_metrics": ["OIC", "Streaming", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Event-driven streaming with decoupled processing.",
        "status": "Valid",
    },
    {
        "code": "G04",
        "name": "Queue-based fan-out decoupling",
        "capture_standard": "OIC Gen3, OCI Queue, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Queue", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#08", "#17"],
        "activates_metrics": ["OIC", "Queue", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Fan-out and resilience without a streaming broker.",
        "status": "Valid",
    },
    {
        "code": "G05",
        "name": "Cloud-native batch data movement",
        "capture_standard": "OCI Data Integration",
        "supported_tool_keys": ["OCI Data Integration"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["OCI Data Integration"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Serverless ETL/ELT or batch data movement.",
        "status": "Valid",
    },
    {
        "code": "G06",
        "name": "Traditional batch data movement",
        "capture_standard": "Data Integrator",
        "supported_tool_keys": ["Data Integrator"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Traditional or marketplace ETL/ELT.",
        "status": "Valid",
    },
    {
        "code": "G07",
        "name": "Streaming-assisted ETL",
        "capture_standard": "OCI Data Integration, OCI Streaming, OCI Functions",
        "supported_tool_keys": ["OCI Data Integration", "OCI Streaming", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#05", "#12"],
        "activates_metrics": ["DI", "Streaming", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Data pipelines with event-driven processing.",
        "status": "Valid",
    },
    {
        "code": "G08",
        "name": "Cloud-native real-time CDC",
        "capture_standard": "Oracle GoldenGate, OCI Streaming, OCI Data Integration",
        "supported_tool_keys": ["Oracle GoldenGate", "OCI Streaming", "OCI Data Integration"],
        "compatible_pattern_ids": ["#05", "#09", "#12"],
        "activates_metrics": ["GoldenGate", "Streaming", "DI"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "CDC or replication with downstream consumption.",
        "status": "Valid",
    },
    {
        "code": "G09",
        "name": "Traditional real-time CDC",
        "capture_standard": "Oracle GoldenGate, Data Integrator",
        "supported_tool_keys": ["Oracle GoldenGate", "Data Integrator"],
        "compatible_pattern_ids": ["#05", "#09", "#12"],
        "activates_metrics": ["GoldenGate", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "CDC or replication with traditional downstream processing.",
        "status": "Valid",
    },
    {
        "code": "G10",
        "name": "Cloud-native app + data hybrid",
        "capture_standard": "OIC Gen3, OCI Data Integration",
        "supported_tool_keys": ["OIC Gen3", "OCI Data Integration"],
        "compatible_pattern_ids": ["#01", "#05", "#12"],
        "activates_metrics": ["OIC", "DI"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when the integration mixes app integration and data movement.",
        "status": "Valid",
    },
    {
        "code": "G11",
        "name": "Traditional app + data hybrid",
        "capture_standard": "OIC Gen3, Data Integrator",
        "supported_tool_keys": ["OIC Gen3", "Data Integrator"],
        "compatible_pattern_ids": ["#01", "#05", "#12"],
        "activates_metrics": ["OIC", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when the integration mixes app integration and traditional data prep.",
        "status": "Valid",
    },
    {
        "code": "G12",
        "name": "DI + Data Integrator coexistence",
        "capture_standard": "OCI Data Integration, Data Integrator",
        "supported_tool_keys": ["OCI Data Integration", "Data Integrator"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["DI", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when serverless and traditional data capabilities coexist.",
        "status": "Valid",
    },
    {
        "code": "G13",
        "name": "Distributed webhook delivery",
        "capture_standard": "OIC Gen3, OCI Queue, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Queue", "OCI Functions"],
        "compatible_pattern_ids": ["#17", "#02"],
        "activates_metrics": ["OIC", "Queue", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Webhook delivery with decoupling and fan-out.",
        "status": "Valid",
    },
    {
        "code": "G14",
        "name": "App integration + serverless transformation",
        "capture_standard": "OIC Gen3, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Functions"],
        "compatible_pattern_ids": ["#01", "#03", "#15"],
        "activates_metrics": ["OIC", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Serverless transformation without broker or queue.",
        "status": "Valid",
    },
    {
        "code": "G15",
        "name": "Stateful orchestration",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#04", "#08"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["Process Automation"],
        "guidance": "Sagas or processes with visible state.",
        "status": "Valid",
    },
    {
        "code": "G16",
        "name": "Lightweight API facade",
        "capture_standard": "OCI Functions",
        "supported_tool_keys": ["OCI Functions"],
        "compatible_pattern_ids": ["#03", "#11"],
        "activates_metrics": ["Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Lightweight exposure with serverless logic.",
        "status": "Valid",
    },
    {
        "code": "G17",
        "name": "Managed events",
        "capture_standard": "OIC Gen3, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#14", "#15", "#17"],
        "activates_metrics": ["OIC", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI Events"],
        "guidance": "Managed events with complementary processing.",
        "status": "Valid",
    },
    {
        "code": "G18",
        "name": "Legacy coexistence",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#06"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Incremental migration with controlled coexistence.",
        "status": "Valid",
    },
]
