"""Workbook-derived governed dictionary and canvas-combination seed data."""

from __future__ import annotations

from typing import Any

DICTIONARY_OPTIONS: list[dict[str, Any]] = [
    {
        "category": "FREQUENCY",
        "code": "FQ01",
        "value": "Cada 5 minutos",
        "description": "Type: Scheduled. Use for: explicit high frequency. Status: Valid.",
        "executions_per_day": 288.0,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ02",
        "value": "Cada 15 minutos",
        "description": "Type: Scheduled. Use for: explicit high frequency. Status: Valid.",
        "executions_per_day": 96.0,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ03",
        "value": "Cada 20 minutos",
        "description": "Type: Scheduled. Use for: explicit high frequency. Status: Valid.",
        "executions_per_day": 72.0,
        "sort_order": 3,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ04",
        "value": "Cada 30 minutos",
        "description": "Type: Scheduled. Use for: explicit high frequency. Status: Valid.",
        "executions_per_day": 48.0,
        "sort_order": 4,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ05",
        "value": "Cada 1 hora",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 24.0,
        "sort_order": 5,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ06",
        "value": "Cada 2 horas",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 12.0,
        "sort_order": 6,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ07",
        "value": "Cada 4 horas",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 6.0,
        "sort_order": 7,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ08",
        "value": "Cada 6 horas",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 4.0,
        "sort_order": 8,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ09",
        "value": "Cada 8 horas",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 3.0,
        "sort_order": 9,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ10",
        "value": "Cada 12 horas",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 2.0,
        "sort_order": 10,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ11",
        "value": "Una vez al día",
        "description": "Type: Scheduled. Use for: standard frequency. Status: Valid.",
        "executions_per_day": 1.0,
        "sort_order": 11,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ12",
        "value": "Semanal",
        "description": "Type: Scheduled. Use for: low frequency. Status: Valid.",
        "executions_per_day": 0.142857,
        "sort_order": 12,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ13",
        "value": "Quincenal",
        "description": "Type: Scheduled. Use for: low frequency. Status: Valid.",
        "executions_per_day": 0.066667,
        "sort_order": 13,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ14",
        "value": "Mensual",
        "description": "Type: Scheduled. Use for: low frequency. Status: Valid.",
        "executions_per_day": 0.033333,
        "sort_order": 14,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ15",
        "value": "Tiempo Real",
        "description": "Type: Event / continuous. Use for: equivalent batch proxy; validate final design. Status: Valid with caution.",
        "executions_per_day": 24.0,
        "sort_order": 15,
        "version": "1.0.0",
    },
    {
        "category": "FREQUENCY",
        "code": "FQ16",
        "value": "Bajo demanda",
        "description": "Type: Occasional. Use for: initial proxy; confirm later. Status: Valid with caution.",
        "executions_per_day": 1.0,
        "sort_order": 16,
        "version": "1.0.0",
    },
    {"category": "TRIGGER_TYPE", "code": "TRG01", "value": "Scheduled", "sort_order": 1, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG02", "value": "REST", "sort_order": 2, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG03", "value": "Event", "sort_order": 3, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG04", "value": "FTP/SFTP", "sort_order": 4, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG05", "value": "DB Polling", "sort_order": 5, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG06", "value": "JMS", "sort_order": 6, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG07", "value": "Kafka", "sort_order": 7, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG08", "value": "Webhook", "sort_order": 8, "version": "1.0.0"},
    {"category": "TRIGGER_TYPE", "code": "TRG09", "value": "SOAP", "sort_order": 9, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX01", "value": "Bajo", "sort_order": 1, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX02", "value": "Medio", "sort_order": 2, "version": "1.0.0"},
    {"category": "COMPLEXITY", "code": "CX03", "value": "Alto", "sort_order": 3, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA01", "value": "OK", "sort_order": 1, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA02", "value": "REVISAR", "sort_order": 2, "version": "1.0.0"},
    {"category": "QA_STATUS", "code": "QA03", "value": "PENDING", "sort_order": 3, "version": "1.0.0"},
    {
        "category": "TOOLS",
        "code": "T01",
        "value": "OIC Gen3",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: messages/month, packs/hour, peak/hour.",
        "is_volumetric": True,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T02",
        "value": "OCI Streaming",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: GB/month, partitions.",
        "is_volumetric": True,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T03",
        "value": "OCI Queue",
        "description": "Type: Add-on core service. Volumetry: direct. Metric/proxy: requests/month.",
        "is_volumetric": True,
        "sort_order": 3,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T04",
        "value": "OCI Functions",
        "description": "Type: Add-on core service. Volumetry: direct. Metric/proxy: invocations and GB-seconds.",
        "is_volumetric": True,
        "sort_order": 4,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T05",
        "value": "OCI Data Integration",
        "description": "Type: Core. Volumetry: direct. Metric/proxy: processed GB and pipeline runs.",
        "is_volumetric": True,
        "sort_order": 5,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T06",
        "value": "Data Integrator",
        "description": "Type: Core / traditional. Volumetry: proxy. Metric/proxy: jobs/month (proxy).",
        "is_volumetric": True,
        "sort_order": 6,
        "version": "1.0.0",
    },
    {
        "category": "TOOLS",
        "code": "T07",
        "value": "Oracle GoldenGate",
        "description": "Type: Core / CDC. Volumetry: proxy. Metric/proxy: changes/month (proxy).",
        "is_volumetric": True,
        "sort_order": 7,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO01",
        "value": "OCI API Gateway",
        "description": "Type: Architectural overlay / proxy. Volumetry: proxy. Typical use: protected API ingress or egress. Capture rule: use one value; separate multiple values with commas.",
        "is_volumetric": True,
        "sort_order": 1,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO02",
        "value": "Process Automation",
        "description": "Type: Architectural overlay / proxy. Volumetry: proxy. Typical use: stateful process or saga orchestration. Capture rule: use one value; separate multiple values with commas.",
        "is_volumetric": True,
        "sort_order": 2,
        "version": "1.0.0",
    },
    {
        "category": "OVERLAYS",
        "code": "AO03",
        "value": "OCI Events",
        "description": "Type: Architectural overlay / proxy. Volumetry: proxy. Typical use: managed event routing. Capture rule: use one value; separate multiple values with commas.",
        "is_volumetric": True,
        "sort_order": 3,
        "version": "1.0.0",
    },
]

CANVAS_COMBINATIONS: list[dict[str, Any]] = [
    {
        "code": "G01",
        "name": "Synchronous app-to-app orchestration",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#01", "#07"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Simple app-to-app integration without additional decoupling.",
        "status": "Valid",
    },
    {
        "code": "G02",
        "name": "Protected synchronous API",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#01", "#03", "#11"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Use when the integration enters or exits through a protected API edge.",
        "status": "Valid",
    },
    {
        "code": "G03",
        "name": "Brokered event backbone",
        "capture_standard": "OIC Gen3, OCI Streaming, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Streaming", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#10", "#14", "#17"],
        "activates_metrics": ["OIC", "Streaming", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Event-driven streaming with decoupled processing.",
        "status": "Valid",
    },
    {
        "code": "G04",
        "name": "Queue-based fan-out decoupling",
        "capture_standard": "OIC Gen3, OCI Queue, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Queue", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#08", "#17"],
        "activates_metrics": ["OIC", "Queue", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Fan-out and resilience without a streaming broker.",
        "status": "Valid",
    },
    {
        "code": "G05",
        "name": "Cloud-native batch data movement",
        "capture_standard": "OCI Data Integration",
        "supported_tool_keys": ["OCI Data Integration"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["OCI Data Integration"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Serverless ETL/ELT or batch data movement.",
        "status": "Valid",
    },
    {
        "code": "G06",
        "name": "Traditional batch data movement",
        "capture_standard": "Data Integrator",
        "supported_tool_keys": ["Data Integrator"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Traditional or marketplace ETL/ELT.",
        "status": "Valid",
    },
    {
        "code": "G07",
        "name": "Streaming-assisted ETL",
        "capture_standard": "OCI Data Integration, OCI Streaming, OCI Functions",
        "supported_tool_keys": ["OCI Data Integration", "OCI Streaming", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#05", "#12"],
        "activates_metrics": ["DI", "Streaming", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Data pipelines with event-driven processing.",
        "status": "Valid",
    },
    {
        "code": "G08",
        "name": "Cloud-native real-time CDC",
        "capture_standard": "Oracle GoldenGate, OCI Streaming, OCI Data Integration",
        "supported_tool_keys": ["Oracle GoldenGate", "OCI Streaming", "OCI Data Integration"],
        "compatible_pattern_ids": ["#05", "#09", "#12"],
        "activates_metrics": ["GoldenGate", "Streaming", "DI"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "CDC or replication with downstream consumption.",
        "status": "Valid",
    },
    {
        "code": "G09",
        "name": "Traditional real-time CDC",
        "capture_standard": "Oracle GoldenGate, Data Integrator",
        "supported_tool_keys": ["Oracle GoldenGate", "Data Integrator"],
        "compatible_pattern_ids": ["#05", "#09", "#12"],
        "activates_metrics": ["GoldenGate", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "CDC or replication with traditional downstream processing.",
        "status": "Valid",
    },
    {
        "code": "G10",
        "name": "Cloud-native app + data hybrid",
        "capture_standard": "OIC Gen3, OCI Data Integration",
        "supported_tool_keys": ["OIC Gen3", "OCI Data Integration"],
        "compatible_pattern_ids": ["#01", "#05", "#12"],
        "activates_metrics": ["OIC", "DI"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when the integration mixes app integration and data movement.",
        "status": "Valid",
    },
    {
        "code": "G11",
        "name": "Traditional app + data hybrid",
        "capture_standard": "OIC Gen3, Data Integrator",
        "supported_tool_keys": ["OIC Gen3", "Data Integrator"],
        "compatible_pattern_ids": ["#01", "#05", "#12"],
        "activates_metrics": ["OIC", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when the integration mixes app integration and traditional data prep.",
        "status": "Valid",
    },
    {
        "code": "G12",
        "name": "DI + Data Integrator coexistence",
        "capture_standard": "OCI Data Integration, Data Integrator",
        "supported_tool_keys": ["OCI Data Integration", "Data Integrator"],
        "compatible_pattern_ids": ["#05", "#12"],
        "activates_metrics": ["DI", "Data Integrator"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Use when serverless and traditional data capabilities coexist.",
        "status": "Valid",
    },
    {
        "code": "G13",
        "name": "Distributed webhook delivery",
        "capture_standard": "OIC Gen3, OCI Queue, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Queue", "OCI Functions"],
        "compatible_pattern_ids": ["#17", "#02"],
        "activates_metrics": ["OIC", "Queue", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Webhook delivery with decoupling and fan-out.",
        "status": "Valid",
    },
    {
        "code": "G14",
        "name": "App integration + serverless transformation",
        "capture_standard": "OIC Gen3, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Functions"],
        "compatible_pattern_ids": ["#01", "#03", "#15"],
        "activates_metrics": ["OIC", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": [],
        "guidance": "Serverless transformation without broker or queue.",
        "status": "Valid",
    },
    {
        "code": "G15",
        "name": "Stateful orchestration",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#04", "#08"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["Process Automation"],
        "guidance": "Sagas or processes with visible state.",
        "status": "Valid",
    },
    {
        "code": "G16",
        "name": "Lightweight API facade",
        "capture_standard": "OCI Functions",
        "supported_tool_keys": ["OCI Functions"],
        "compatible_pattern_ids": ["#03", "#11"],
        "activates_metrics": ["Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Lightweight exposure with serverless logic.",
        "status": "Valid",
    },
    {
        "code": "G17",
        "name": "Managed events",
        "capture_standard": "OIC Gen3, OCI Functions",
        "supported_tool_keys": ["OIC Gen3", "OCI Functions"],
        "compatible_pattern_ids": ["#02", "#14", "#15", "#17"],
        "activates_metrics": ["OIC", "Functions"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI Events"],
        "guidance": "Managed events with complementary processing.",
        "status": "Valid",
    },
    {
        "code": "G18",
        "name": "Legacy coexistence",
        "capture_standard": "OIC Gen3",
        "supported_tool_keys": ["OIC Gen3"],
        "compatible_pattern_ids": ["#06"],
        "activates_metrics": ["OIC"],
        "activates_volumetric_metrics": True,
        "recommended_overlays": ["OCI API Gateway"],
        "guidance": "Incremental migration with controlled coexistence.",
        "status": "Valid",
    },
]
